<a href="https://colab.research.google.com/github/AbhilashPal/XOR-Neural-Network/blob/master/Numpy_Dropout.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **Import Numpy **

In [0]:
import numpy as np

### Define Sigmoid **Function**

In [0]:
def sigmoid(x,deriv = False):
	if(deriv==True):
		return x*(1-x)
	return 1/(1+np.exp(-x))

### **Form Dummy Input Data**

In [9]:
X = np.random.rand(1,3)
X.shape

(1, 3)

In [11]:
X

array([[0.18408486, 0.60009536, 0.07382265]])

### **Initialize Weights and Biases**

In [0]:
W1 = np.random.rand(3,4)
W2 = np.random.rand(4,4)
W3 = np.random.rand(4,1)

b1 = np.random.rand(1,4)
b2 = np.random.rand(1,4)
b3 = np.random.rand(1,1)

### **Forward Propagation**

In [0]:
#layer 1
Z1 = np.dot(X,W1) + b1

In [14]:
Z1.shape

(1, 4)

In [0]:
A1 = sigmoid(Z1)

In [0]:
#layer 2
Z2 = np.dot(A1,W2) + b2
A2 = sigmoid(Z2)

#layer 3
Z3 = np.dot(A2,W3) + b3
A3 = sigmoid(Z3)

In [19]:
A3

array([[0.96067345]])

### **Dropout Implementation :**


*   Dropout of 0.5 in between first and second hidden layer 
*   Dropout of 0.6 in between second hidden and output layer



In [0]:
keep_prob1 = 0.5
keep_prob2 = 0.6

In [0]:
d2 = np.random.rand(A2.shape[0],
                    A2.shape[1]) < keep_prob1

In [38]:
d2

array([[ True, False, False,  True]])

In [41]:
#similarly
d3 = np.random.rand(A3.shape[0],
                    A3.shape[1]) < keep_prob2
d3

array([[False]])

### **Applying Dropout in Forward Prop :**

In [0]:
#layer 1
Z1 = np.dot(X,W1) + b1
A1 = sigmoid(Z1)
#layer 2
Z2 = np.dot(A1,W2) + b2
A2 = sigmoid(Z2)
A2 = np.multiply(A2,d2)
A2/=keep_prob1
#layer 3
Z3 = np.dot(A2,W3) + b3
A3 = sigmoid(Z3)
A3 = np.multiply(A3,d3)
A3/=keep_prob2

In [43]:
A3

array([[0.]])