In [8]:
import numpy as np
from __future__ import print_function

 Loading our Data:
---

In [9]:
X = np.array([[0,0],[0,1],[1,0],[1,1]])
Y = np.array([[0,1,1,0]])

Initializing our Weights :
---

In [10]:
np.random.seed(1)
W1 = np.random.randn(3,2)*0.0001
b1 = np.ones((3,1))
W2 = np.random.randn(1,3)*0.0001
b2 = np.ones((1,1))

Helper Functions :
---

In [11]:
def sigmoid(x):
    return 1/(1+np.exp(x))
def sigmoid_gradient(x):
    return x*(1-x)

In [12]:
print(X)
print(Y)

[[0 0]
 [0 1]
 [1 0]
 [1 1]]
[[0 1 1 0]]


Gradient Descent :
---

In [16]:
learning_rate = 0.001
m = 4
for iteration in range(100000):
    
    #forward propagation
    
    #layer1
    Z1 = np.dot(W1,X.T)+b1
    A1 = sigmoid(Z1)
    #layer2
    Z2 = np.dot(W2,A1)+b2
    A2 = sigmoid(Z2)
    
    #backpropagation
    
    dZ2 = Y-A2
    dW2 = np.dot(dZ2,A1.T)/m
    db2 = np.sum(dZ2,axis=1,keepdims=True)/m
    
    dZ1 = np.dot(dW2.T,dZ2)*sigmoid_gradient(Z1)
    dW1 = np.dot(dZ1,X )/m
    db1 = np.sum(dZ1,axis=1,keepdims=True)/m
    
    
    #checking if shapes are correctly preserved
    
    assert(dZ2.shape==Z2.shape)
    assert(dW2.shape==W2.shape)
    assert(db2.shape==b2.shape)
    assert(dZ1.shape==Z1.shape)
    assert(dW1.shape==W1.shape)
    assert(db1.shape==b1.shape)
    
    #update parameters
    
    W1 = W1 + learning_rate*dW1
    W2 = W2 + learning_rate*dW2
    b1 = b1 + learning_rate*db1
    b2 = b2 + learning_rate*db2
    
    # print every 10k
    if(iteration%10000==0):
        print(A2)

[[1.86522372e-27 1.86483469e-27 1.86493937e-27 1.86455038e-27]]
[[4.24699685e-30 4.24605948e-30 4.24624689e-30 4.24530965e-30]]
[[9.67014410e-33 9.66788138e-33 9.66821410e-33 9.66595173e-33]]
[[2.20183085e-35 2.20128426e-35 2.20134291e-35 2.20079642e-35]]
[[5.01343004e-38 5.01210992e-38 5.01221272e-38 5.01089287e-38]]
[[1.14152641e-40 1.14120787e-40 1.14122579e-40 1.14090732e-40]]
[[2.59918368e-43 2.59841608e-43 2.59844718e-43 2.59767977e-43]]
[[5.91817737e-46 5.91633078e-46 5.91638456e-46 5.91453845e-46]]
[[1.34753168e-48 1.34708827e-48 1.34709754e-48 1.34665425e-48]]
[[3.06824468e-51 3.06718201e-51 3.06719792e-51 3.06613557e-51]]
